name: universal_eticaretsitesisatisi_app
description: "Dinamik Eticaret Sitesi Satisi WebView"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.7.0
  webview_flutter_android: ^3.15.0
  webview_flutter_wkwebview: ^3.13.0
  permission_handler: ^11.3.1
  url_launcher: ^6.2.5
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.13.1"

# İKON AYARLARI - BURASI KRİTİK
flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/logo.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
